version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - youtube-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin     # <-- Mongo Express Web Login username
      - ME_CONFIG_BASICAUTH_PASSWORD=pass      # <-- Mongo Express Web Login password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    networks:
      - youtube-network

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-streamlit-app
    ports:
      - "8501:8501"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=pass
    depends_on:
      - mongo
    networks:
      - youtube-network

networks:
  youtube-network:
    driver: bridge
